### ISSUE TITLE
Improve performance of test pipeline

### ISSUE THREAD

**Issue by behackl** [kbredies/gratopy#5]
According to https://github.com/kbredies/gratopy/actions/runs/2557973874, the pipeline takes about an hour to run. It might be possible to cut that down a little bit running the tests in parallel via `pytest-xdist` -- definitely worth a try.

**Comment by kbredies** [comment]
Added `pytest-xdist` to the test workflow. A first run did not indicate an essential speedup, but parallel tests do not hurt.
